#ifndef __STATUS_H__
#define __STATUS_H__

typedef enum
{
  CREATED = 201,
  SUCCESS = 200,
} StatusCode;

typedef enum
{
  NO_ERROR = 0,

  ERROR = 400,
  ERR_UNAUTHORIZED = 401,
  ERR_USERNAME_EXIST = 402,
  ERR_USER_NOT_FOUND = 403,
  ERR_PASSWORD_INCORRECT = 404,
  ERR_CODE_ACTIVATE_INCORRECT = 405,
  ERR_CODE_ACTIVATE_INCORRECT_OVER = 406,
  ERR_PASSWORD_INCORRECT_OVER = 407,
  ERR_USER_NOT_ACTIVATE = 408,
  ERR_USER_BLOCKED = 409,
  ERR_OLD_PASSWORD_INCORRECT = 410,
  ERR_PASSWORD_FORMAT_INVALID = 411,

  ERR_MEMORY_FAILED = 500,

  ERR_DOMAIN_NOT_FOUND = 600,
  ERR_IPADDR_NOT_FOUND = 601,
} ErrorCode;

void error(ErrorCode code);

#endif
